services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=store_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - ./container/data/mysql:/var/lib/mysql